### ISSUE TITLE
FAQ page:  Featured image and text is not displaying in faq page after added.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Hose-Force#102]
1. Applicable for news page also.

![faq_image](https://cloud.githubusercontent.com/assets/13309730/8960414/72b803e6-362d-11e5-9846-de0085113e27.png)

**Comment by mahender-sowedane** [comment]
If not required for featured image in FAQ's page please take as enhancement.

**Comment by ravititan** [comment]
For intro text in any page we are not giving image provision...
