### ISSUE TITLE
Banner section: NEVER use ShortenText() as per standard implementation

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Hose-Force#15]
![untitled-1](https://cloud.githubusercontent.com/assets/13309730/8906799/1e79af7c-348f-11e5-9198-ebd212a97943.jpg)

**Comment by ravititan** [comment]
this is post description on banner.. if we dont limit it, it will spillout of banner height...

**Comment by mahender-sowedane** [comment]
I raised it based on KB articles,please confirm with your TL and fix it.

**Comment by ravititan** [comment]
without shortentext banner will distort....
