### ISSUE TITLE
Products Categories page: Products categories titles are clipped.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Hose-Force#30]
![products_clip01](https://cloud.githubusercontent.com/assets/13309730/8908374/744d0188-3499-11e5-8daa-cfb76aa56a63.png)

**Comment by mahender-sowedane** [comment]
Give me a reason why won't fix this.

**Comment by ravititan** [comment]
not for this

**Comment by mahender-sowedane** [comment]
'not for this' means i can't understand what your saying, but still issues not fixed on devices and browsers. have a look on screens

![screenshot_2015-08-12-13-04-48](https://cloud.githubusercontent.com/assets/13309730/9223525/89b039a6-4118-11e5-9be4-cd764a91e9ae.png)

![products archive _desktop](https://cloud.githubusercontent.com/assets/13309730/9223540/ac777864-4118-11e5-8cb0-a4366abb6969.png)
