### ISSUE TITLE
Banner section: Always use Slick Carousel for the Banner rotator as per project scope.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Hose-Force#39]
Per standard implementaion:
https://knowledgebase.titanweb.com.au/implementation-practices/page-section-contents/banners

![slick_banner](https://cloud.githubusercontent.com/assets/13309730/8926187/6a7b64e6-352b-11e5-92d5-c9734006011a.png)

**Comment by ravititan** [comment]
I am using same banner carousel for all my projects...

**Comment by mahender-sowedane** [comment]
It should be developed using Slick carousel as per the project scope.

**Comment by mahender-sowedane** [comment]
Still not fixed

![slick_banner](https://cloud.githubusercontent.com/assets/13309730/9242475/43e2dbd6-419f-11e5-82a6-8baef8ca3117.png)

**Comment by mahender-sowedane** [comment]
Closed this bug as TL changed the project scope.
