### ISSUE TITLE
General: Getting horizontal scroll bar on mobile devices.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Hose-Force#4]
Devices: Samsung E7 and I Pod

![horizontal_scroll001](https://cloud.githubusercontent.com/assets/13309730/8905407/a70bc624-3483-11e5-9773-b09d3433c1e1.png)

**Comment by mahender-sowedane** [comment]
Still not fixed.

![screenshot_2015-08-07-15-44-37](https://cloud.githubusercontent.com/assets/13309730/9133847/7894896a-3d1c-11e5-9a16-bc8f9408b721.png)

![screenshot_2015-08-07-15-44-45](https://cloud.githubusercontent.com/assets/13309730/9133848/7895a12e-3d1c-11e5-90de-f5c0cb722e5b.png)

**Comment by mahender-sowedane** [comment]
Still not fixed.

![scroolbr](https://cloud.githubusercontent.com/assets/13309730/9242681/13b6ecf0-41a3-11e5-875f-a41a49c013ff.png)

**Comment by ravititan** [comment]
Issues has been Resolved
