### ISSUE TITLE
Banner section: Missing background overlay for banners.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Hose-Force#45]
![banner_upload01](https://cloud.githubusercontent.com/assets/13309730/8928212/7835a02e-353a-11e5-814c-13692ffe43a2.png)

**Comment by ravititan** [comment]
please explain...

**Comment by mahender-sowedane** [comment]
Due to absence of black color overlay, banner caption is not clearly visible. Have a look at the attached screenshot.

![banner](https://cloud.githubusercontent.com/assets/13309730/9135387/65c79602-3d2a-11e5-96f8-8b61dad3d0ea.png)

**Comment by ravititan** [comment]
if client doesnt provide any title and descsription... then overlay will look odd...
