### ISSUE TITLE
Home page: Getting Console errors (9 Errors)

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Hose-Force#60]
![home_page_con](https://cloud.githubusercontent.com/assets/13309730/8930582/d8813620-354c-11e5-8ad0-b2d75c00ee4f.png)

**Comment by mahender-sowedane** [comment]
Still issue not fixed,please refer screenshot
Getting Console errors (11 Errors)

![homepage_con](https://cloud.githubusercontent.com/assets/13309730/9133204/63d1d212-3d17-11e5-852e-35b92894cc70.png)

**Comment by ravititan** [comment]
4 errors fixed.... remaining wont fix
