### ISSUE TITLE
Welcome content section(Home page):  Unnecessary horizontal lines are displaying after clicking on 'view more' button.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Hose-Force#66]
![home_page_linesun01](https://cloud.githubusercontent.com/assets/13309730/8951431/4e84e9ea-35eb-11e5-8336-16fc44660222.png)

**Comment by mahender-sowedane** [comment]
Give me a reason why won'tfix this.

**Comment by ravititan** [comment]
Issues Fixed
