### ISSUE TITLE
Products Categories-single pages: Unnecessary gap is occurring on product single pages.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Hose-Force#88]
Browsers and devices
"http://hoseforce.stage.titanweb.com.au/products/camlocks/product-name-goes-here-for-this-long-and-very-long/"

![gapbd](https://cloud.githubusercontent.com/assets/13309730/8957239/bad18b06-361a-11e5-8070-6e780dca7f5b.png)

**Comment by mahender-sowedane** [comment]
Still not fixed in I pad and I pad mini.

![2015-08-07_1607](https://cloud.githubusercontent.com/assets/13309730/9134108/d8148ae6-3d1e-11e5-8318-894070b008fd.png)

**Comment by ravititan** [comment]
We never manage document height, It will increase depends on the content.

**Comment by mahender-sowedane** [comment]
And also have a look on above screenshot "Download product catalogue" is overlapping with footer.

**Comment by ravititan** [comment]
it was fixed
