### ISSUE TITLE
Lead-ins(Home page): Video Pop-up window is not displaying properly when switch to landscape view. Part of the page can't be seen.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Hose-Force#9]
Devices: Samsung E7 (L) and I Pod (L).

![video_windl01](https://cloud.githubusercontent.com/assets/13309730/8905868/7e354168-3487-11e5-8663-9b308ba5f581.png)

**Comment by mahender-sowedane** [comment]
When switch to landscape view getting horizontal scroll bar,still window is not displaying properly.

![screenshot_2015-08-07-15-47-24](https://cloud.githubusercontent.com/assets/13309730/9133767/da5d9cbe-3d1b-11e5-949f-7fba1c2e752f.png)

**Comment by mahender-sowedane** [comment]
Still issue not fixed, have a look on screenshot.

![screenshot_2015-08-13-09-55-41](https://cloud.githubusercontent.com/assets/13309730/9242630/357ca330-41a2-11e5-9144-473a420b1be5.png)

**Comment by ravititan** [comment]
AS of now Its working fine.But some some time it happens because video was loading in iframe. we can't style content under iframes.
